package com.frugalbin.common.enums;

public enum TemplateNames
{
	REGISTRATION_CONFIRMATION,
	FRUGALBIN_WELCOME,
	SEND_USER_REQUEST_LINK,
	USER_REQUEST_LINK,
	BOOKING_CONFIRMATION,
	SEND_FRUGALBIN_MESSAGE
}
